/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114765-gbaf17c15be-20240409"
#endif /* AVUTIL_FFVERSION_H */
